- hosts: HAProxy
  vars_files:
          - "/home/fidato/Ansible/task12/myvariable.yml"
  tasks:
  - name: Checking if HA-Proxy is present
    command: haproxy -version
    register: haproxy_version
    changed_when: haproxy_version != 0
    failed_when: False

  - name: Installing HAproxy
    package:
            name: "haproxy"
            state: present

  - name: Starting HAProxy
    service:
            name: "haproxy"
            state: started


  - name: Configuring HAProxy
    template:
            src: "/home/fidato/Ansible/task12/haproxy.cfg"
            dest: "/etc/haproxy/haproxy.cfg"


- hosts: WebServer
  tasks:
  - name: Installing PHP
    package:
            name: "php"
            state: present


  - name: Installing Apache Webserver
    package:
            name: "httpd"
            state: present

  - name: Starting Apache Webserver
    service:
            name: "httpd"
            state: started
  
  - name: Copying the webcontent
    copy:
            src: "/home/fidato/Ansible/task12/index.php"
            dest: "/var/www/html/"


- hosts: HAProxy
  tasks:
  - name: Restarting HAProxy
    service:
            name: "haproxy"
            state: restarted
